services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    env_file:
      - .env
    # The commented out section below is an example of how to define a PostgreSQL
    # database that your application can use. `depends_on` tells Docker Compose to
    # start the database before your application. The `db-data` volume persists the
    # database data between container restarts. The `db-password` secret is used
    # to set the database password. You must create `db/password.txt` and add
    # a password of your choosing to it before running `docker-compose up`.
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: nailspadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Maruko12345!
    # secrets:
    #   - db-password
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
# secrets:
#   db-password:
#     file: db/password.txt
